### ISSUE TITLE
saves 404 page without comment as if it were a game

### ISSUE THREAD

**Issue by fallenguru** [MrV2K/WHDLoad-Download-Tool#11]
If WHDLoad-Download-Tool, operating over HTTP, gets a 404, it will download the HTML of the error page and save it as the file without complaining. Consequently, it will show the file as present afterwards.

WHDLoad-Download-Tool should register 404's, and output an error for the entry.
Ideally some sort of CRC check functionality would be included, or file size at the very least.

**Comment by MrV2K** [comment]
I'm adding CRC32 checking to the checks which should eliminate the problem. It might take a few weeks as I'm working on another project at the moment.

**Comment by MrV2K** [comment]
Fixed in v1.3
