### ISSUE TITLE
Request: Create update packs

### ISSUE THREAD

**Issue by ZXDunny** [MrV2K/WHDLoad-Download-Tool#12]
Just a small thing now that I'm using the tool to maintain my collection - when updates are performed, it might be nice to be able to produce an update pack - LHA/LZX for preference - of just the changed WHDLoad archives for easier transferring to the Amiga. A nice bonus would be an unpack script that would automatically unpack the games/demos/whatnot and delete obsolete files when it gets there.

As it stands at the moment, after each update I have to make a note of what changed, and then copy over only those files unless I re-copy the entire lot in one go each time.

**Comment by MrV2K** [comment]
You can save the download list as a text file in the latest release.
