### ISSUE TITLE
Path Bug

### ISSUE THREAD

**Issue by manic232** [MrV2K/WHDLoad-Download-Tool#17]
I think I have found a small path bug.

My WHDLoad files are stored in the following path S:\Gaming & Emulation\Commodore\Amiga\WHDLoad_Installs

I have 3 folders in that path:

WHDLoad_Demos
WHDLoad_Games
WHDLoad_Mags

When I hit the download button it correctly identifies any missing files (SecondSamurai_v1.3a_AGA_1624.lha in this example), however the games are stored in the following location

S:\Gaming & Emulation\Commodore\Amiga\WHDLoad_InstallsWHDLoad_Games\S\SecondSamurai_v1.3a_AGA_1624.lha

It created a folder called WHDLoad_InstallsWHDLoad_Games in S:\Gaming & Emulation\Commodore\Amiga It seems to be missing the \ between WHDLoad_Installs and WHDLoad_Games 

![image](https://github.com/MrV2K/WHDLoad-Download-Tool/assets/62509071/f3c35779-52d9-4646-abb2-64bd3f173b0c)

Hope that makes sence!

**Comment by MrV2K** [comment]
Do you have the last forward slash at the end of your parent path?
![image](https://github.com/MrV2K/WHDLoad-Download-Tool/assets/71010565/204dcb1b-3d26-49a8-a9e0-83a4016172f9)
