### ISSUE TITLE
Demo files downloading even when Demo is unticked

### ISSUE THREAD

**Issue by andrea-petrucci-1975** [MrV2K/WHDLoad-Download-Tool#18]
I am using v1.3.2, I have Demo unticked in folder settings
![image](https://github.com/MrV2K/WHDLoad-Download-Tool/assets/12188987/7e87a2d7-2606-4a5b-bba5-871eed14096b)

but when I hit download it still wants to download some Demo files.
![image](https://github.com/MrV2K/WHDLoad-Download-Tool/assets/12188987/d4c87131-0aa4-43c6-bc1c-646d2f53d05f)

NOTE: the files it tries to download are both BETA (which I want) and DEMO (which I don't want), the problem certainly arises from this but it should be ensured that both BETA and DEMO are downloaded only when the user has selected both voices

**Comment by MrV2K** [comment]
I know that it's not ideal, but I would have to restructure the whole code and redesign the UI to do this for the sake of 6 files. Too much work for not much benefit I'm afraid.

**Comment by andrea-petrucci-1975** [comment]
no need for UI redesign: 
if user tick BETA but don't tick DEMO no download of DMEO BETA

restructure the whole code I haven't looked at the code but I think with a case construct it shouldn't be a challenging change

**Comment by MrV2K** [comment]
Fixed in new release.
