### ISSUE TITLE
Croatian language always highlighted

### ISSUE THREAD

**Issue by Grassinix** [MrV2K/WHDLoad-Download-Tool#19]
Despite unchecking and leaving only the selected languages (in my case English and Polish) and saving the configuration, after restarting WHDLoad Download Tools I still have the Croatian language selected. I attach a screenshot. Tested on 3 computers with win 10 and 11.
![obraz](https://github.com/user-attachments/assets/00e60339-982d-41bd-a0c7-3da9c2970a6e)

**Comment by MrV2K** [comment]
Confirmed.

**Comment by MrV2K** [comment]
Fixed in new release
