### ISSUE TITLE
default download dir refers to some hardcoded non universal location

### ISSUE THREAD

**Issue by michalkolodziejski** [MrV2K/WHDLoad-Download-Tool#2]
the `Save folders` Parent field contains by default location that looks like a hardcoded dev-machine constant.

![Main window](https://www.dropbox.com/s/xg1on01lpmxqyl6/Zrzut%20ekranu%202022-01-19%20o%2008.41.39.jpg?raw=1)

proposal - change to `CWD`\Download to make it a universal location

**Comment by MrV2K** [comment]
The program sets the default download path to the home folder that the program is stored in plus \Download as a subfolder. This is done to stop users downloading into the home folder if the defaults aren't changed. If you use the set button it will download straight to the selected folder. How would you want this behaviour to change?

**Comment by MrV2K** [comment]
No reply
