### ISSUE TITLE
FTP Directory listings not working

### ISSUE THREAD

**Issue by NemoN** [MrV2K/WHDLoad-Download-Tool#3]
The login is working, but then the directory listing is failing silently.
It is possible to enable the "passive FTP mode"?

**Comment by MrV2K** [comment]
FTP is set to passive by default. Setting to active, stops communication. I think that it's firewall related. I can replicate the connection problems by setting my firewall access to private on a public connection. Setting the connection to public seems to let all communication happen. It's really frustrating as I'm using standard Windows API commands. I can't understand why the connection still fails for some users. The only other thing is. the connection may need some delays for slower connections.

**Comment by HVR88** [comment]
I don't keep a firewall on my test Windows 10 VM at all.  Neither 8a nor unstable are able to get a directory listing from FTP.  You should enable debug output of some kind.
