### ISSUE TITLE
FTP wouldn't work at first.

### ISSUE THREAD

**Issue by AmigaNoob** [MrV2K/WHDLoad-Download-Tool#4]
I'm using WHDLoadTool08a.zip

FTP wouldn't work at first. So I edited the default.prefs file, changing line 9

FTP_Folder = Retroplay WHDLoad Packs
to
FTP_Folder = /Retroplay WHDLoad Packs/

Everything works fine then.

**Comment by HVR88** [comment]
That doesn't work.  The thought that the author simply missed the root path in the preference file seems a little far-fetched as this would cause an immediate problem for 100% of people testing.

That said, since there's absolutely no debug or FTP status output, it's not possible to tell what's going on at all.

I can say with certainty that the issues aren't firewall related as people keep going on about in the EAB forum.

**Comment by JEmlay** [comment]
Is this project dead?  The FTP Server is up and responding but it rejects the login.  Also, the above mentioned change didn't help.

```
Connected to grandis.nu.
220 TURRAN (glFTPd 2.12 (Dec 25 2021) 64BiT Linux+TLS(OpenSSL 3.0.1 14 Dec 2021)+SSP) ready.
530 Please log in first.
User (grandis.nu:(none)): ftp
331 Password required for ftp.
Password:
530- The server has been shut down, try again later.
530
Connection closed by remote host.
```

**Comment by MrV2K** [comment]
The project is alive but I'm figuring out how to add http downloads as they will solve the download problems. I'm also adding download by category and support for FAT32 drives 256 file limit.

To fix the current login problem, open the 'default.prefs' file and change the ftp_server line to ftp.grandis.nu. That will fix the current login problems.

**Comment by JEmlay** [comment]
I see.  Yup, that fixed it.  Greatly appreciate it!  

Wow, yeah, this program rocks.  Reminds me of how I code things always thinking of how to make it easier for the end user.

Top notch!

**Comment by HVR88** [comment]
The file/data list pane is never populated even after the dat file is supposedly updated after the FTP connection.

**Comment by JEmlay** [comment]
Worked flawlessly right out of the gate!

**Comment by MrV2K** [comment]
Fixed in latest release.
