### ISSUE TITLE
Feature request:  Possible WHDload filters

### ISSUE THREAD

**Issue by roc-eab** [MrV2K/WHDLoad-Download-Tool#5]
Hello,

First and foremost, **thank you** for the hard work to release such a good tool !

Just as an idea and if this would be feasible and appropriate, a few filters that might be useful in some corner-case. 
I list them all to give you full visibility, but this request would be for the first three ;-) I have removed the filters already there.

More Important:
1. Memory: '512K','512KB','1MB','2MB','8MB','12MB','15MB','Slow','LowMem'

Less important:
3. Audios = 'MT32','NoSounds','NoMusic','NoVoice','NoSpeech'
4. Disks = '1Disk','2Disk','3Disk','4Disk'

not-important at all:
5. GameVersions = 'AltLevels','Censored','EasyPlay','Enhanced','NoMovie','Nointro','PreRelease','Uncensored'
6. Videos = 'HiRes','LoRes'
7. AmigaVersions = 'NONAGA','1200','A1200Version','A1000','A600Pack'
8.  WHDLoadVersions = ''Repacked'

The reason for that is because I do have different installations. For the first two (AGA and OCS) I simply use all the WHDLoad (the latter without AGAs of course). These two suits all my real miggies and the MiSTer, however there would also be two more difficult ones. 

1. One for the FPGAs that requires up to two HDFs of 4GB each - e.g. Minimig, MiST, FleaFPGA, Replay and UnAmiga.
9. One for the PS-Vita (up to 4 HDFs, 2GB each)

To keep the size to a minimum, among the other selection (Two languages only, Files-installs, Fast memory..) I normally select  only the most suitable version of them - e.g. highest RAM, NoVoice or NoSpeech, 1Disk, HiRes

I know it is a lot and the GUI space is already filled with filters, so If the right approach would be to finalise them manually, of course I would understand :-)

Thank you in advance for your consideration and, importantly, for this great tool!

**Comment by MrV2K** [comment]
I can certainly implement quite a lot of that. I just need to think about the UI. I don't want to make it too complicated. I'll have to ponder for a while.

**Comment by MrV2K** [comment]
Added in v1.1 release.
