### ISSUE TITLE
Finnish language games are not being placed in language folders

### ISSUE THREAD

**Issue by LemaruX** [MrV2K/WHDLoad-Download-Tool#7]
When downloading games from all languages, the Finnish titles are not being placed in a language folder. 

All other language games are being placed in the relevant folders, but the Finnish ones remain in the root of the download directory. 

<img width="152" alt="image" src="https://user-images.githubusercontent.com/34491084/211629312-ddf2f26a-e7f2-488f-a667-77a684bdf43d.png">

Issue can be replicated.

**Comment by MrV2K** [comment]
Fixed in v1.2
